### ISSUE TITLE
error creating json file in save folder

### ISSUE THREAD

**Issue by LHAnh2002** [yuceltoluyag/Rise-of-Kingdoms-Bot#11]
How to fix this error

**Comment by yuceltoluyag** [comment]
Please do not forget to provide the requested information in your bug reports [BUG template ](https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml)  Because I'm not **clairvoyant** : )  However, using my oracle skills, I see that you have not created a "save" folder in your project home directory. 
 
If you don't know how to use it, you can read my comment. https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/issues/5#issuecomment-1577295867
