### ISSUE TITLE
cannot load building pos

### ISSUE THREAD

**Issue by BigWildGamer** [yuceltoluyag/Rise-of-Kingdoms-Bot#8]
When i press buildposition button the bot run but no image in the window.

in prompt:

```
Get City Image
        * [01:59:28] init building position
        * [01:59:28] init view
        * [01:59:28] game is not running, try to start game
        * [01:59:34] done
Exception in thread Thread-27 (after_image_load):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\marci\Desktop\Rise-of-Kingdoms-Bot-main\gui\selected_device_frame.py", line 292, in after_image_load
    image = parent.bot.get_city_image().resize((640, 360), Image.ANTIALIAS)
                                                           ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by LHAnh2002** [comment]
I have an error that I can't load the game, do you have any solution?

**Comment by haonguyen-archisketch** [comment]
try reinstall lib Pillow 9.5.0
```
pip uninstall Pillow
pip install Pillow==9.5.0
```

**Comment by ndhao164** [comment]
try reinstall lib Pillow 9.5.0
```
pip uninstall Pillow
pip install Pillow==9.5.0
```

**Comment by yuceltoluyag** [comment]
This problem is related to python version and library. Our friend has given the solution. Please provide the requested information next time.


**Screenshots**
If available, attach screenshots to help explain your issue.

**Desktop (please fill in the following information):**
 - OPERATING SYSTEM: [e.g. Window, Linux, Mac]
 - Emulator and version [e.g. Bluestacks xxx, LDPLAYer xxx]
 - Python Version [e.g. 3.11.3]

Updated and tested

![image](https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/assets/16064131/7a52f7bd-93d3-452b-986f-8278a8061429)
